# // catch和finally的具体用法

#### catch----------

##### // 一般reject和promise.then(null,onReject)一样

```JavaScript
let p=Promise.reject("foo")

let rejectHandler=function (e){
  // console.log("p is reject");
  setTimeout(console.log, 0,"reject");
}

p.then(null,rejectHandler)

p.catch(rejectHandler)
//对p使用onReject处理函数和使用catch方法结果相同
```

![image-20220927074829607](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20220927074829607.png)

##### // 用catch创建新的期约,与用onReject处理函数创建方式一样

```JavaScript
//用于建立新期约的初始期约
let p=Promise.reject("foo")
//和then一样,不传入任何处理函数会进行浅复制
let p2=p.catch()

setTimeout(console.log,0,p2)

//注意需要用箭头函数把设置的期约返回
let p3=p.catch(()=>Promise.resolve(7))

setTimeout(console.log,0,p3)


//传入字符串或者数字会被resolve方法包装
let p4=p.catch(()=>"foo")
setTimeout(console.log,0,p4)


//返回时抛出错误会新建一个reject的期约
let p5=p.catch(()=>{throw new Error("error")})
setTimeout(console.log,0,p5)
```

![image-20220927075245069](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20220927075245069.png)



#### finally-----------------

##### // finally与catch有很大不同,因为finally不论期约状态变化为解决还是拒绝都会执行,这一点和finally没有办法知道期约的状态有关

```JavaScript
let p1=Promise.resolve(8)
let p2=Promise.reject("foo")

let onFinally=function(e){
  setTimeout(console.log,0,"finally")
}

p1.finally(onFinally)
p2.finally(onFinally)
// finally看起来不是一个处理函数
```

![image-20220927080912560](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20220927080912560.png)



##### // finally同样可以创建新的期约,不过新的期约与then或者catch方法创建的有很大的不同

```JavaScript
let p=Promise.resolve(7)

// 与then和catch方法创建新的期约最大不同在于,有关得到期约为resolve状态的方法均失效,变成浅复制

let p1=p.finally()
setTimeout(console.log,0,p1)

let p2=p.finally(()=>{})
setTimeout(console.log,0,p2)

let p3=p.finally(()=>"foo")
setTimeout(console.log,0,p3)

let p4=p.finally(()=>Promise.resolve(7))
setTimeout(console.log,0,p4)

let p5=p.finally(()=>undefined)
setTimeout(console.log,0,p5)
```

![image-20220927081634735](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20220927081634735.png)

##### // 对于创建新期约的状态为pendding和reject的则不会影响

```JavaScript
let p=Promise.resolve(7)

let p2=p.finally(()=>Promise.reject("foo"))
setTimeout(console.log,0,p2)

let p3=p.finally(()=>{throw "foo"})
setTimeout(console.log,0,p3)

let p4=p.finally(()=>new Promise(()=>{}))
setTimeout(console.log,0,p4)
```

![image-20220927082442864](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20220927082442864.png)

##### // 即使是pendding状态,一旦变成resolve状态依旧会执行浅复制

```JavaScript
let p=Promise.resolve(7)

// 返回1s后变成resolve状态的期约
let p2=p.finally(()=>new Promise((resolve,reject)=>{
  setTimeout(resolve,1000)
}))

setTimeout(console.log,0,p2)
// 2s 之后
setTimeout(console.log,2000,p2)
```

![image-20220927083227703](C:\Users\35392\AppData\Roaming\Typora\typora-user-images\image-20220927083227703.png)







